### ISSUE TITLE
Database bug with latest wordpress french release

### ISSUE THREAD

**Issue by jeromefiot** [GeekPress/WP-Quick-Install#15]
I do have a bug during this step which freeze the process : "Database Installation in Progress..."
Any idea ? same issue anybody ?

**Comment by jeromefiot** [comment]
Little Up !!? any news ?

**Comment by GeekPress** [comment]
Hi there,

The issue is solved in the new release (1.4).

Enjoy!

**Comment by geoffyuen** [comment]
I did a quick test and it still gets stuck at the db install. From my browser console:

     Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by WPsmart** [comment]
Hi

Still I have This issue, i downloaded 1.4.1 and try to install wp. but its stuck in "Database Installation in Progress..."

Can you fix it?

Thanks

**Comment by WPsmart** [comment]
I think its my server problem, 
i tested this on my pc (localhost). its working well, but not working on my server, its will be wordpress download problem, i will check it

Thanks for this awesome script :)

**Comment by GeekPress** [comment]
@WPsmart Yes, sometimes it doesn't working with specific server configuration but I don't know the reason :/

**Comment by WPsmart** [comment]
@GeekPress

Yes i think its server file download error, i using digitalocean.com. i opened support ticket, if i fix this i will reply here

Thanks for quick reply :)
